# Generated by Django 3.1.1 on 2020-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200906_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='no'),
            preserve_default=False,
        ),
    ]
